version: '2.0'
services:
  mysql-server:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=MiBank
      - MYSQL_PASSWORD=MiBank
      - MYSQL_DATABASE=MiBankDB
volumes:
  mysql_data:
    driver: local
