-- MySQL Script generated by MySQL Workbench
-- dom 06 may 2018 17:59:11 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MiBankDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `MiBankDB` ;

-- -----------------------------------------------------
-- Schema MiBankDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MiBankDB` DEFAULT CHARACTER SET utf8 ;
USE `MiBankDB` ;

-- -----------------------------------------------------
-- Table `MiBankDB`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MiBankDB`.`Employee` ;

CREATE TABLE IF NOT EXISTS `MiBankDB`.`Employee` (
  `id` INT NOT NULL,
  `user_name` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MiBankDB`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MiBankDB`.`Account` ;

CREATE TABLE IF NOT EXISTS `MiBankDB`.`Account` (
  `bank` INT(4) NOT NULL,
  `office` INT(4) NOT NULL,
  `control` INT(2) NOT NULL,
  `id` INT(10) NOT NULL DEFAULT AUTO_INCREMENT,
  `currency` VARCHAR(3) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (`bank`, `office`, `control`, `id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MiBankDB`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MiBankDB`.`User` ;

CREATE TABLE IF NOT EXISTS `MiBankDB`.`User` (
  `account_bank` INT(4) NOT NULL,
  `account_office` INT(4) NOT NULL,
  `account_control` INT(2) NOT NULL,
  `account_id` INT(10) NOT NULL,
  `dni` VARCHAR(9) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` INT NOT NULL,
  `phone_prefix` VARCHAR(5) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `updated_at` TIMESTAMP NOT NULL DEFAULT current_timestamp ON UPDATE current_timestamp,
  UNIQUE INDEX `DNI_UNIQUE` (`dni` ASC),
  PRIMARY KEY (`account_bank`, `account_office`, `account_control`, `account_id`),
  CONSTRAINT `fk_User_Account1`
    FOREIGN KEY (`account_bank` , `account_office` , `account_control` , `account_id`)
    REFERENCES `MiBankDB`.`Account` (`bank` , `office` , `control` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MiBankDB`.`Transfer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MiBankDB`.`Transfer` ;

CREATE TABLE IF NOT EXISTS `MiBankDB`.`Transfer` (
  `id` INT NOT NULL,
  `account_from` VARCHAR(24) NULL,
  `amount` DECIMAL NOT NULL,
  `description` VARCHAR(45) NULL,
  `employee_involved` INT NULL,
  `account_bank` INT(4) NOT NULL,
  `account_office` INT(4) NOT NULL,
  `account_control` INT(2) NOT NULL,
  `account_id` INT(10) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Transfer_Employee1_idx` (`employee_involved` ASC),
  INDEX `description_idx` (`description` ASC),
  INDEX `fk_Transfer_Account1_idx` (`account_bank` ASC, `account_office` ASC, `account_control` ASC, `account_id` ASC),
  CONSTRAINT `fk_Transfer_Employee1`
    FOREIGN KEY (`employee_involved`)
    REFERENCES `MiBankDB`.`Employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transfer_Account1`
    FOREIGN KEY (`account_bank` , `account_office` , `account_control` , `account_id`)
    REFERENCES `MiBankDB`.`Account` (`bank` , `office` , `control` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
